project_id = "ohuejjhakbncfzhhdfhn"

[functions.here_route]
verify_jwt = false

[functions.here_weather_alerts_along_route]
verify_jwt = false

[functions.get_mapbox_token]
verify_jwt = true

[functions.here_geocode]
verify_jwt = false