# Podfile for Trucker Pathfinder - Mapbox Navigation SDK v2
# Platform requirements: iOS 14.0+

platform :ios, '14.0'
use_frameworks!

# Required for Mapbox Navigation SDK v2
install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  # Capacitor Core
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  
  # Mapbox Navigation SDK v2 (full turn-by-turn navigation)
  pod 'MapboxNavigationCoreResource', '~> 3.7.1'
  pod 'MapboxNavigation', '~> 2.18.0'
  pod 'MapboxMaps', '~> 10.18.0'
  
  # Speech synthesis for voice guidance
  pod 'MapboxSpeech', '~> 2.1.1'
  
  # Offline downloads
  pod 'MapboxNavigationNative', '~> 316.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Required for Xcode 15+
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      
      # Fix module stability issues
      config.build_settings['SWIFT_VERSION'] = '5.0'
      
      # Enable bitcode = NO for Mapbox
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
